[SH] 21.04.12 과제 업로드
OLOZLO/algo-study pull request #100
Opened 2021-04-15 16:30 UTC by girawhale

내가 이거때문에.... class를 만들었숨미다...
후....

2021-04-15 19:40 UTC, pro-popo requested changes
### 🥛 물병
* 세상 깔끔한 코드에 감탄을 금치할 수 없었습니다. 👍👍
### 🎣 낚시왕
* 함수까지 작성해서 완벽한 객체지향 코드로 만들어 줄거라 믿어요 쌤! 😋
### ⚖ 중량제한
* 이제 다익스트라보다 이분탐색이 먼저 생각날 것 같아요 🤗🤗

2021-04-15 19:40 UTC, pro-popo commented on src/_210413/boj17143/Main_girawhale.java
> +            shark.speed %= mod[(shark.dir + 1) / 2]; // mod값만큼 이동하면 처음 위치로 돌아오기 때문에 나머지만큼만 이동하도록 설정
입력값을 생성자 활용해서 저장하는 것부터 배열 mod를 사용해서 값을 가져오는 것까지, 생각도 못한 방식이라 신선했어요!
깔끔, 직관적 그 자체... 넘 멋집니다 송쌤 😍

2021-04-15 19:40 UTC, pro-popo commented on src/_210413/boj17143/Main_girawhale.java
> +        while (pos < C) {
송쌤 이거 넘 길어여 😗😗 얼른 기능별로 함수화 해주세요!! 😣😣

2021-04-15 19:40 UTC, pro-popo commented on src/_210413/boj17143/Main_girawhale.java
> +                } else map[shark.y][shark.x] = shark; // 현재 칸에 상어 없으니까 그냥 넣기 ㄱ
쏭쌤! 할 말이 있어여!!! 🤗
여기 중복 코드가 보여요 😗😗 `map[shark.y][shark.x] = shark` 
그리구, 개인적으로 어떤 조건일 때 map에 shark를 저장하는지 한 눈에 안 읽히는 것 같아요 😫

아래와 같은 로직은 어떨까요?? 😚
변수명은 살짝쿵 애매하지만... 😋
```suggestion
		Shark sharkInMap = map[shark.y][shark.x];
		if (sharkInMap == null || (sharkInMap != null && (sharkInMap.size < shark.size))) 
		    map[shark.y][shark.x] = shark;
```

2021-04-15 19:40 UTC, pro-popo commented on src/_210413/boj1939/Main_girawhale.java
> +                if (a[1] < m || visit[a[0]]) continue; // 주어진 값보다 작은 도로는 탐색하지 못함. pass
쏭쌤!! a[1]이 먼가여! a[0]가 먼가여!!! 🤨🤨🤨

2021-04-15 19:52 UTC, girawhale commented on src/_210413/boj1052/Main_girawhale.java
> +    - 이유 : N이 증가할 수 있는 최대 수는 10^7이기 때문에 1억을 넘지 않아 가능
아맞넹?

2021-04-15 19:59 UTC, girawhale commented on src/_210413/boj17143/Main_girawhale.java
> +        while (pos < C) {
착시입미다

2021-04-16 05:58 UTC, yeongjin-Jung commented on src/_210413/boj17143/Main_girawhale.java
> +            shark.speed %= mod[(shark.dir + 1) / 2]; // mod값만큼 이동하면 처음 위치로 돌아오기 때문에 나머지만큼만 이동하도록 설정
mod를 사용한다... 오늘도 한수 배우고 갑니다 슨생님

2021-04-16 05:58 UTC, yeongjin-Jung commented on src/_210413/boj1939/Main_girawhale.java
> +                if (a[1] < m || visit[a[0]]) continue; // 주어진 값보다 작은 도로는 탐색하지 못함. pass
a 불편 합니다 !!!

2021-04-17 14:46 UTC, pro-popo approved these changes

2021-04-18 10:53 UTC, merged