[JA] 21.04.13 HW
OLOZLO/algo-study pull request #97
Opened 2021-04-14 09:36 UTC by pro-popo

잘 부탁드립니담😁

2021-04-14 12:40 UTC, ddb8036631 commented on src/_210413/boj1052/Main_ja.java
> +		int result = 1 << res.get(res.size() - K);
**N=21, K=1** 를 예로 들면, 얘네를 다 합치면 물병은 [16, 4, 1] 이(이진수 10101) 되고, 리스트 res 에는 [0,2,4] 가 들어가게 됩니다. 최종 물병을 1개로 맞추기 위해선 가장 큰 16과 합쳐질 16짜리 물병이 필요합니다. 하지만, 남아있는 [4, 1] 물병을 이용해야 하므로, 16 - 4 - 1 해서 11개의 물병이 필요한 로직 맞나요?

물병 K개를 남기기 위해 리스트 res를 뒤부터 K개를 만족시키는 물병의 용량을 찾아, 역으로 개수를 맞춰가는 방법 잘 봤습니다. 말로 설명하기 어려울 것 같네요. 그림 그려주세요 ㅎㅎ

2021-04-14 12:40 UTC, ddb8036631 commented on src/_210413/boj17143/Main_ja.java
> + * [골드4] 중량제한
17143 - 낚시왕
1939 - 중량제한 입니당. 둘이 바꼈어요

2021-04-14 12:40 UTC, ddb8036631 commented on src/_210413/boj17143/Main_ja.java
> + *    	 - 도착지에 도착하면 중력 출력 후 return
**우선순위 큐**를 이용해 각 정점까지 **최대 중량 제한**을 둬서 풀 수 있다는 점 배워갑니다.

2021-04-14 12:40 UTC, ddb8036631 commented on src/_210413/boj17143/Main_ja.java
> +	}
1. 스트링을 잘라 스트림으로 만들고,
2. 매퍼함수로 매핑시키고,
3. 다시 int[] 배열로 변환하고

하는 과정에서 시간이 많이 걸릴 거 같은데, 혹시 StringTokenizer 를 쓰지 않고 굳이 함수를 하나 더 만들어서 배열에 담는 이유가 따로 있나요? StringTokenizer가 시간, 메모리적으로도 좋고, 사용하기도 더 편할 것 같아서요

2021-04-14 12:40 UTC, ddb8036631 commented on src/_210413/boj1939/Main_ja.java
> +	}
상어맵을 하나 더 만들어서 이쪽에다가 옮겨진 상어들을 표시하면 코드도 깔끔해지고 가독성도 좋아지는군요.. 배워갑니다

2021-04-14 12:40 UTC, ddb8036631 commented on src/_210413/boj1939/Main_ja.java
> +			for (int j = 0; j < C; j++) {
매번 RxC 크기를 다 돌 필요없이, 상어만 저장되어있는 배열이나 리스트만 돌면서 이동시키는 방법이 시간 단축에 도움이 되지 않을까 생각합니다.

2021-04-15 04:38 UTC, girawhale commented on src/_210413/boj17143/Main_ja.java
> + * [골드4] 중량제한
밥버😟

2021-04-15 08:15 UTC, pro-popo commented on src/_210413/boj1052/Main_ja.java
> +		int result = 1 << res.get(res.size() - K);
사실 무성쌤 코드였나요? 저보다 설명을 잘하시네욬ㅋㅋㅋㅋ 
이해한 로직이 맞습니다! 완벽해요! 👍👍 
ㅋㅋㅋㅋ이해하셨는데 왜 그림을 요구하세여! ㅋㅋ 그려드립니다. ㅎㅎㅎㅎ

![image](https://user-images.githubusercontent.com/52408122/114835710-cfeacd80-9e0c-11eb-825d-70315d61cea9.png)

위의 그림과 같이, 합치지 못한 물병(1의 수)를 리스트 res에 담습니다. 
`res [0, 1, 3]`  → _값은 cnt 입니다._

만약 **K=2**이면,
③과 ②를 선택하고, ①번 물병만 남겠죠?
이때, 남은 물병(①)을 제거해 주기 위해 ②번 물병과 합쳐줘야 합니다.

그래서,
필요한 물병(②) 수 - 가지고 있는 물병(①) 수를 계산하면 아래와 같습니다.
`2^1 - 2^0 = 1`

2021-04-15 08:16 UTC, pro-popo commented on src/_210413/boj17143/Main_ja.java
> + * [골드4] 중량제한
진짜 밥버.... ㅠㅜㅠ 수정하겠습니다 😂😂

2021-04-15 08:50 UTC, pro-popo commented on src/_210413/boj17143/Main_ja.java
> +	}
무성쌤 말이 맞습니다! 🤗
사실 StringTokenizer를 사용하는게 시간, 메모리 면에서 더 효율적입니다.

그런데도 저런 식으로 사용하는 이유는,
함수형 프로그래밍에 익숙해지려고 습관처럼 쓰고 있지만, 사실  **가독성 측면에서 이점이 크기 때문에** 사용하고 있습니다.

변수를 선언하고 초기화 코드에서, 
변수에 '해당 input값을 int형으로 변환한 후 저장.' 보다는
변수에 '해당 input값을 저장.' 이 개인적으로 읽기 쉽다고 느꼈습니다!

사실 알고에서 입력값 받을 때는 큰 차이가 없다고 생각해서 편한거 써도 괜찮다고 생각합니다!
저도 테스트 해봤었는데, StringTokenizer가 좀 더 빨랐지만 큰 문제를 줄 만큼 차이는 나지 않더라고요!
오히려 intput[i] 쓰면서 i를 실수로 기입할까봐 무섭습니다...😅😅

2021-04-15 08:51 UTC, pro-popo commented on src/_210413/boj1939/Main_ja.java
> +			for (int j = 0; j < C; j++) {
와 꿀팁 감사합니다! 확실히 맵을 다 도는 것보다 따로 저장하는게 더 효율적이겠네요 🤔🤔

2021-04-15 17:19 UTC, girawhale requested changes

2021-04-15 17:19 UTC, girawhale commented on src/_210413/boj1052/Main_ja.java
> +			result -= 1 << res.get(next);
로직자체는 맞지만 코드가 이해하기에 직관적이지 않아 오류났을때 디버깅도 어려울 수 있고, 나중에 다시보면 헷갈리기 쉬울듯

2021-04-15 17:19 UTC, girawhale commented on src/_210413/boj17143/Main_ja.java
> +
필드로 만들거면 speed, size 등으로 한눈에 알기 쉬운 변수명이 좋다고 생각

2021-04-15 17:19 UTC, girawhale commented on src/_210413/boj1939/Main_ja.java
> +		// 다익스트라
다익스트라 상상도 못해봤는데... 아이디어 좋네여👍

2021-04-15 17:19 UTC, girawhale commented on src/_210413/boj1939/Main_ja.java
> +				dist[next.v] = Math.max(w, dist[next.v]);
어차피 dist[next.v]보다 작으면 continue처리가 되어있는데, max할 필요없이 그냥 w를 넣으면 되지 않을가여?

2021-04-15 18:19 UTC, pro-popo commented on src/_210413/boj1052/Main_ja.java
> +			result -= 1 << res.get(next);
맞습니다.. 저 아이디어를 구현하면서 중간중간에 멘탈이 자꾸 나가더라고요..😂😂
역시 bitCount가 최고ㅎㅎㅎㅎ

2021-04-15 18:21 UTC, pro-popo commented on src/_210413/boj17143/Main_ja.java
> +
왠만하면 입력값이랑 형식 맞추고 싶어서 그랬는데, 생각해보니까 걍 모든 변수명 자체를 직관적으로 바꾸면 되겠네요 🙌🙌
반영해서 바꾸겠습니다!!

2021-04-15 18:24 UTC, pro-popo commented on src/_210413/boj1939/Main_ja.java
> +				dist[next.v] = Math.max(w, dist[next.v]);
와 그러게요!! 불필요한 부분이었네요 ㅠㅠ 지적 감사합니당 😆😆
바로 수정 각각!

2021-04-15 18:34 UTC, girawhale approved these changes

2021-04-16 08:18 UTC, pro-popo commented on src/_210413/boj1939/Main_ja.java
> +		// 다익스트라
t

2021-04-18 10:55 UTC, merged