[YJ] HOMEWORK
OLOZLO/algo-study pull request #98
Opened 2021-04-14 12:32 UTC by yeongjin-Jung

리뷰 부탁합니다 라고 쓰면 되는건강

2021-04-14 13:02 UTC, ddb8036631 commented on src/_210413/boj19939/Main_jyj.java
> +  2. 시간 복잡도 : O(1/log(max(w)) * (N + M))
이분 탐색 시간복잡도가 **O(logW)** , 인접 리스트를 사용한 BFS의 시간복잡도가 **O(N+M)** 이고, 매번 반으로 나누면서 BFS 탐색을 실행하니 최종 시간복잡도는 **O(logW * (N + M))** 가 될 것 같습니다.

2021-04-15 15:35 UTC, pro-popo reviewed
### 🥛 물컵
* 저랑 유사한 방식으로 풀었네요! 🤗🤗
* bitCount 함수도 한 번 사용해 보세요! 저도 보고 신세계였답니다 😅😅
### ⚖ 중량제한
* 전체적으로 충분히 고민하고, 깔끔하게 생각을 정리한 점이 좋았습니다! 👍
* 저도 이분 탐색으로 한 번 도전해봐야겠어요 ! 🙌🙌

2021-04-15 15:35 UTC, pro-popo commented on src/_210413/boj19939/Main_jyj.java
> +				}
동의합니다! 배열 graph에 이쁘게 Node 형식으로 저장했으니까 for-each문을 사용하는게 낫다고 생각합니다!
`visited[next.end] == false` 이 코드도 `!visited[next.end]`로 표현할 수 있겠네요 😆😆

2021-04-15 18:02 UTC, girawhale requested changes

2021-04-15 18:02 UTC, girawhale commented on src/_210413/boj19939/Main_jyj.java
> +			min = Math.min(c, min);
이분탐색의 시간복잡도는 O(logN)이기 때문에 몇 번 차이나지 않음
그냥 0부터 10^9까지 돌려도 괜찮음

오히려 입력마다 갱신하기 때문에 지연될 가능성도 존재

2021-04-15 18:02 UTC, girawhale commented on src/_210413/boj19939/Main_jyj.java
> +				if (graph[temp].get(i).weight >= mid && visited[graph[temp].get(i).end] == false) {
```suggetion
				if (graph[temp].get(i).weight >= mid && !visited[graph[temp].get(i).end]) {
```

2021-04-16 05:47 UTC, yeongjin-Jung commented on src/_210413/boj19939/Main_jyj.java
> +				}
아 감사합니다 가독성 확인확인 좋은 방법이네요

2021-04-16 05:48 UTC, yeongjin-Jung commented on src/_210413/boj19939/Main_jyj.java
> +package _210413.boj19939;
실수했네요 ㅠㅠ

2021-04-16 05:48 UTC, yeongjin-Jung commented on src/_210413/boj19939/Main_jyj.java
> +  2. 시간 복잡도 : O(1/log(max(w)) * (N + M))
시간 복잡도를 잘 몰라서 참고하는데 큰 도움이 되었습니다.

2021-04-16 05:54 UTC, yeongjin-Jung commented on src/_210413/boj1052/Main_jyj.java
> +		} else {
출력하고 종료하는게 더 깔끔하고 좋네요 앞으로 그렇게 하는 습관을 가져보겠슴돠

2021-04-16 05:55 UTC, yeongjin-Jung commented on src/_210413/boj19939/Main_jyj.java
> +	인접행렬은 N*N의 메모리 공간을 사용하므로 N에 너무 큰 수가 들어오면 메모리 초과가 발생할 수 있다는것을 알았습니다.
메모리 초과만 확인하고 계산은 따로 안해봤는데 계산하면 확실히 넘는걸 확인 할 수 있군요 감사합니다

2021-04-16 05:55 UTC, yeongjin-Jung commented on src/_210413/boj1052/Main_jyj.java
> +	 * 2. 시간복잡도 : 0
어엇? 시간복잡도 넘 어렵,,,,ㅠ

2021-04-16 05:56 UTC, yeongjin-Jung commented on src/_210413/boj19939/Main_jyj.java
> +				if (graph[temp].get(i).weight >= mid && visited[graph[temp].get(i).end] == false) {
ㅋㅋㅋㅋㅋ 더 짧게 노력해보겠슴돠

2021-04-18 10:54 UTC, merged